angular.module('myApp', []).controller('clientsCtrl', function($scope) {
$scope.total = 17442.514;
$scope.trees = 296;
$scope.quotations = [ { key : 'Duplex', value : '' },
                      { key : 'A4 Paper', value : '' },
                      { key : 'Books', value : ''}, 
                      { key : 'Folding Cartons', value : ''}, 
                      { key : 'White Paper Copies', value : ''}, 
                      { key : 'Old Corrugated Containers (Cartons)', value : ''}, 
                      { key : 'Newsprint', value : '' },
                      { key : 'Polythene', value : '' } ];

$scope.clients = [{
            location: 'Raymonds, Civil Lines, Allahabad',
            title: 'Raymond',
            img: 'raymond',
            key1: 'Duplex : ',
            key2: 'Cartons : ',
            key3: 'Polythene : ',
            key4: 'PET : ',
            key5: 'Paper : ',
            key6: '',
            value1: '48.485 kg',
            value2: '230.565 kg',
            value3: '11.89 kg',
            value4: '1.645 kg',
            value5: '151 kg',
            value6: ''
        },{
            location: 'Killer, Civil Lines, Allahabad',
            title: 'Killer',
            img: 'killer',
            key1: 'Cartons : ',
            key2: 'Polythene : ',
            key3: 'Mix : ',
            key4: 'Paper : ',
            key5: '',
            key6: '',
            value1: '12.760 kg',
            value2: '2.720 kg',
            value3: '8.165 kg',
            value4: '14.185 kg',
            value5: '',
            value6: ''
        },{
            location: 'Adidas, Civil Lines, Allahabad',
            title: 'Adidas',
            img: 'adidas',
            key1: 'Cartons : ',
            key2: 'Polythene : ',
            key3: 'Paper : ',
            key4: '',
            key5: '',
            key6: '',
            value1: '125.242 kg',
            value2: '3.625 kg',
            value3: '16.435 kg',
            value4: '',
            value5: '',
            value6: ''
        },{
            location: 'Arrow, Civil Lines, Allahabad',
            title: 'Arrow',
            img: 'arrow',
            key1: 'Cartons : ',
            key2: 'Polythene : ',
            key3: 'Duplex : ',
            key4: 'Paper : ',
            key5: '',
            key6: '',
            value1: '117 kg',
            value2: '13.835 kg',
            value3: '9.06 kg',
            value4: '80.804 kg',
            value5: '',
            value6: ''
        },{
            location: 'Liberty, Civil Lines, Allahabad',
            title: 'Liberty',
            img: 'liberty',
            key1: 'Cartons : ',
            key2: 'Polythene : ',
            key3: 'Paper : ',
            key4: '',
            key5: '',
            key6: '',
            value1: '116.62 kg',
            value2: '2.100 kg',
            value3: '70 kg',
            value4: '',
            value5: '',
            value6: ''
        },{
            location: '48/6, Strachey Road, Civil Lines, Allahabad',
            title: 'Madan Lifestyle and Collection',
            img: 'madan',
            key1: 'Paper Waste : ',
            key2: 'Polythene : ',
            key3: 'Cartons : ',
            key4: 'Duplex : ',
            key5: 'Books : ',
            key6: '',
            value1: '3588 kg',
            value2: '544 kg',
            value3: '563.2 kg',
            value4: '540.1 kg',
            value5: '37 kg',
            value6: ''
        },{
            location: 'Civil Lines, Allahabad',
            title: 'Lenovo',
            img: 'lenovo',
            key1: 'Paper Waste : ',
            key2: 'Polythene : ',
            key3: 'Books : ',
            key4: '',
            key5: '',
            key6: '',
            value1: '41.665 kg',
            value2: '0.305 kg',
            value3: '57 kg',
            value4: '',
            value5: '',
            value6: ''
        },{
            location: 'Maharaja Footwear KP Kakkar Road,South Malaka ,Allahabad',
            title: 'Maharaja Footwear',
            img: 'maharaja',
            key1: 'Recyclable Material : ',
            key2: '',
            key3: '',
            key4: '',
            key5: '',
            key6: '',
            value1: '150 kg',
            value2: '',
            value3: '',
            value4: '',
            value5: '',
            value6: ''
        },{
            location: 'Patanjali,Naini ,Allahabad',
            title: 'Patanjali',
            img: 'patanjali',
            key1: 'Cartons : ',
            key2: 'Polythene : ',
            key3: 'Paper : ',
            key4: '',
            key5: '',
            key6: '',
            value1: '486.73 kg',
            value2: '1.765 kg',
            value3: '609.4 kg',
            value4: '',
            value5: '',
            value6: ''
        },{
            location: 'Sasta Mart, Civil Lines, Allahabad',
            title: 'Sasta Mart',
            img: 'sasta_mart',
            key1: 'Duplex : ',
            key2: 'Cartons : ',
            key3: 'Polythene : ',
            key4: 'Paper : ',
            key5: '',
            key6: '',
            value1: '27.54 kg',
            value2: '156 kg',
            value3: '24.475 kg',
            value4: '153 kg',
            value5: '',
            value6: ''
        },{
            location: 'Anant Bazaar,Naini ,Allahabad',
            title: 'Anant Bazaar',
            img: 'anant_bazaar',
            key1: 'Recyclable Material : ',
            key2: 'Cartons : ',
            key3: 'Polythene : ',
            key4: 'PET : ',
            key5: 'Paper : ',
            key6: '',
            value1: '22 kg',
            value2: '60.975 kg',
            value3: '0.945 kg',
            value4: '0.320 kg',
            value5: '30 kg',
            value6: ''
        },{
            location: 'Mod Fash ,Allahabad',
            title: 'Mod Fash',
            img: 'mod-fash',
            key1: 'Cartons : ',
            key2: 'Duplex : ',
            key3: 'Polythene : ',
            key4: '',
            key5: '',
            key6: '',
            value1: '16.735 kg',
            value2: '15.4 kg',
            value3: '4.145 kg',
            value4: '',
            value5: '',
            value6: ''
        },{
            location: 'Manoj garments ,Allahabad',
            title: 'Manoj Garments',
            img: 'manoj',
            key1: 'Cartons : ',
            key2: 'Duplex : ',
            key3: 'Polythene : ',
            key4: '',
            key5: '',
            key6: '',
            value1: '4.47 kg',
            value2: '6.26 kg',
            value3: '2.53 kg',
            value4: '',
            value5: '',
            value6: ''
        },{
            location: 'Chaddha electric works',
            title: 'Chaddha electic works',
            img: 'Chaddha_electric_works',
            key1: 'Recyclable Material : ',
            key2: '',
            key3: '',
            key4: '',
            key5: '',
            key6: '',
            value1: '91 kg',
            value2: '',
            value3: '',
            value4: '',
            value5: '',
            value6: ''
        },{
            location: 'Housing, Allahabad',
            title: 'Housing',
            img: 'housing',
            key1: 'Recyclable Material : ',
            key2: '',
            key3: '',
            key4: '',
            key5: '',
            key6: '',
            value1: '660 kg',
            value2: '',
            value3: '',
            value4: '',
            value5: '',
            value6: ''
        },{
            location: 'Motilal & Sons, Allahabad',
            title: 'Motilal & Sons',
            img: 'mns',
            key1: 'Cartons : ',
            key2: 'Polythene : ',
            key3: 'Paper : ',
            key4: '',
            key5: '',
            key6: '',
            value1: '228.200 kg',
            value2: '4.3 kg',
            value3: '636 kg',
            value4: '',
            value5: '',
            value6: ''
        },{
            location: 'Prince Dresses, Allahabad',
            title: 'Prince Dresses',
            img: 'prince',
            key1: 'Mix : ',
            key2: 'Duplex : ',
            key3: 'Books : ',
            key4: 'Cartons : ',
            key5: 'Newspaper : ',
            key6: 'Polythene : ',
            value1: '148.465 kg',
            value2: '141.445 kg',
            value3: '32.530 kg',
            value4: '15.695 kg',
            value5: '14.295 kg',
            value6: '72.730 kg'
        },{
            location: 'Mangalam, Allahabad',
            title: 'Mangalam',
            img: 'mangalam',
            key1: 'Carton : ',
            key2: 'Duplex : ',
            key3: 'Mix : ',
            key4: 'Polythene : ',
            key5: 'Books : ',
            key6: 'Newspaper : ',
            value1: '22.705 kg',
            value2: '6.120 kg',
            value3: '4.445 kg',
            value4: '1.775 kg',
            value5: '26.1 kg',
            value6: '2.425 kg'
        },{
            location: 'Ambika, Allahabad',
            title: 'Ambika Collections',
            img: 'ambika',
            key1: 'Carton : ',
            key2: 'Duplex : ',
            key3: 'Mix : ',
            key4: 'Polythene : ',
            key5: '',
            key6: 'Newspaper : ',
            value1: '7.315 kg',
            value2: '8.660 kg',
            value3: '17.120 kg',
            value4: '3.825 kg',
            value5: '',
            value6: '1 kg'
            
        },{
            location: 'Jai Lakshmi Collections, Allahabad',
            title: 'Jai Lakshmi Collections',
            img: 'jl',
            key1: 'Mix : ',
            key2: 'Duplex : ',
            key3: '',
            key4: '',
            key5: 'Newspaper : ',
            key6: 'Polythene : ',
            value1: '4.540 kg',
            value2: '6.115 kg',
            value3: '',
            value4: '',
            value5: '2.880 kg',
            value6: '4.120 kg'
        },{
            location: 'Lal garments, Allahabad',
            title: 'Lal garments',
            img: 'lal',
            key1: 'Mix : ',
            key2: '',
            key3: '',
            key4: '',
            key5: '',
            key6: 'Polythene : ',
            value1: '9.7 kg',
            value2: '',
            value3: '',
            value4: '',
            value5: '',
            value6: '1.945 kg'
        },{
            location: 'Saree Sansar, Allahabad',
            title: 'Ma Vidyavasini Saree Sansar',
            img: 'saree',
            key1: 'Carton : ',
            key2: 'Mix : ',
            key3: 'Polythene : ',
            key4: 'Duplex : ',
            key5: 'Paper : ',
            key6: '',
            value1: '14.975 kg',
            value2: '17.83 kg',
            value3: '13.83 kg',
            value4: '5.160 kg',
            value5: '98.86 kg',
            value6: ''
        },{
            location: 'Kesarwani Electricals, Allahabad',
            title: 'Kesarwani Electricals',
            img: 'kesarwani',
            key1: 'Carton : ',
            key2: 'Polythene : ',
            key3: 'Mix : ',
            key4: 'Paper : ',
            key5: '',
            key6: '',
            value1: '219.942 kg',
            value2: '8.068 kg',
            value3: '18.200 kg',
            value4: '181.4 kg',
            value5: '',
            value6: ''
        },{
            location: 'Allahabad',
            title: 'Unik Bazar',
            img: 'unik-bazar',
            key1: 'Paper : ',
            key2: 'Polythene : ',
            key3: '',
            key4: '',
            key5: '',
            key6: '',
            value1: '409.3 kg',
            value2: '45.7 kg',
            value3: '',
            value4: '',
            value5: '',
            value6: ''
        },{
            location: 'Civil Lines, Allahabad',
            title: 'Octave',
            img: '',
            key1: 'Cartons : ',
            key2: 'Polythene : ',
            key3: 'Paper : ',
            key4: '',
            key5: '',
            key6: '',
            value1: '22.580 kg',
            value2: '0.950 kg',
            value3: '23.4 kg',
            value4: '',
            value5: '',
            value6: ''
        },{
            location: 'Civil Lines, Allahabad',
            title: 'Eldee motors',
            img: '',
            key1: 'Cartons : ',
            key2: 'Polythene : ',
            key3: 'Plastic : ',
            key4: 'Paper : ',
            key5: '',
            key6: '',
            value1: '369.945 kg',
            value2: '63.765 kg',
            value3: '28.21 kg',
            value4: '737.48 kg',
            value5: '',
            value6: ''
        },{
            location: 'Allahabad',
            title: 'V Mart',
            img: '',
            key1: 'Paper : ',
            key2: 'Poly : ',
            key3: '',
            key4: '',
            key5: '',
            key6: '',
            value1: '175 kg',
            value2: '118 kg',
            value3: '',
            value4: '',
            value5: '',
            value6: ''
        },{
            location: 'Allahabad',
            title: 'Van Heusen',
            img: '',
            key1: 'Paper : ',
            key2: '',
            key3: '',
            key4: '',
            key5: '',
            key6: '',
            value1: '171 kg',
            value2: '',
            value3: '',
            value4: '',
            value5: '',
            value6: ''
        },{
            location: 'Allahabad',
            title: 'G Food',
            img: '',
            key1: 'Paper : ',
            key2: '',
            key3: '',
            key4: '',
            key5: '',
            key6: '',
            value1: '222.5 kg',
            value2: '',
            value3: '',
            value4: '',
            value5: '',
            value6: ''
        },{
            location: 'Allahabad',
            title: 'Vishal Mega Mart',
            img: '',
            key1: 'Paper : ',
            key2: '',
            key3: '',
            key4: '',
            key5: '',
            key6: '',
            value1: '4000 kg',
            value2: '',
            value3: '',
            value4: '',
            value5: '',
            value6: ''
        },{
            location: 'Allahabad',
            title: 'Jalan',
            img: 'jalan',
            key1: 'Paper : ',
            key2: 'Polythene : ',
            key3: '',
            key4: '',
            key5: '',
            key6: '',
            value1: '156 kg',
            value2: '13 kg',
            value3: '',
            value4: '',
            value5: '',
            value6: ''
        },{
            location: 'Allahabad',
            title: 'Shri Ram departmental stores',
            img: 'shri_ram',
            key1: 'Paper : ',
            key2: '',
            key3: '',
            key4: '',
            key5: '',
            key6: '',
            value1: '272.3 kg',
            value2: '',
            value3: '',
            value4: '',
            value5: '',
            value6: ''
        }
    ];
});